spring:
  application:
    name: indexing-app

  groovy:
    template:
      enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: secret
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true

  security:
    oauth2:
      client:
        registration:
          content-app:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: indexing-app
            client-secret: hFL6Bvdg4ZQBSYGXrtPO0veebUKcGpHd
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/Alive/protocol/openid-connect/token

content-app:
  api:
    base-url: http://localhost:8081

logging:
  level:
    root: INFO
    dk.runerne: DEBUG

server:
  port: 8086

api:
  base-path: /api/v1

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha